# July 15 2019 aws storage cost for ncsa genomics projects:
```text
    Note that the monthly cost of 3 TB of s3 storage 
    is comparable to the daily cost of the 
    largest hard drive (5 TB) in the table below.
```
[Amazon s3 pricing](https://aws.amazon.com/s3/pricing/) <br>
[Amazon EBS (Elastic Block Storage) pricing](https://aws.amazon.com/ebs/pricing/) <br> 
[Amazon EC2 pricing](https://aws.amazon.com/ec2/pricing/on-demand/) <br>
[Amazon EC2-EBS pricing estimator (new & improved)](https://aws.amazon.com/blogs/aws/check-it-out-new-aws-pricing-calculator-for-ec2-and-ebs/) <br>
<br>
***
## Estimate S3 bucket upload of 3.0 TiB iforge DataPacks/human
0.023 per GB month <br>
3000 * 0.023 = 69.00 <br>
[amazon cloud storage costs blog page](https://blog.cloudability.com/aws-s3-understanding-cloud-storage-costs-to-save/) <br>
<br>
***
## Estimate *volumes* cleanup savings
These Volumes were attached to stopped EC2 instances but were still being charged. <br>

IOPS = Input / Output Operations Per Second (per month of availability)  <br>
IOPS drives price = 0.125 per GB mo + 0.065 per provisioned IOPS-month <br>

| *volume ID* | *size (GB)* | *IOPS* | *== GB + IOPS (estimated cost/mo)* |
|-------------|--------|------|------|
|vol-0ac07a7336d647a4f|5000|15000|625.00 + 975.00 = 1600.00|
|vol-0fa00f6bda7cbc4c7|250|10000|31.25 + 650.00 = 681.25|
|vol-0a95364d9a46a8a47|250|10000|31.25 + 48.75 = 80.00|
|vol-07366977d2b43d0f0|600|100|75.00 + 6.50 = 81.50|
|vol-0c3638a22a1d9ec6a|600|100|75.00 + 6.50 = 81.50|
|-------------|--------|------|------|
|Total|6700|various|2524.25|

#### *volumes were successfully removed Monday July 15*

In [7]:
import os
import numpy as np
print('\n\tnp.random.randint(0, 10, 100)\n\n', np.random.randint(0, 10, 100).reshape(10,10))


	np.random.randint(0, 10, 100)

 [[3 2 7 6 3 4 6 8 6 8]
 [8 2 7 3 2 1 0 4 8 6]
 [8 5 6 9 4 0 7 2 8 2]
 [9 1 7 7 8 4 2 0 6 0]
 [1 4 3 6 1 9 3 8 2 1]
 [0 9 6 8 9 4 8 8 0 7]
 [9 3 7 0 4 8 3 9 1 7]
 [6 0 7 1 0 0 5 4 0 9]
 [8 5 9 4 1 2 9 3 4 6]
 [1 5 5 7 1 2 6 1 2 6]]
